// src/context/LanguageContext.tsx
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ES' | 'EN' | 'IT';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: string) => void;
  changeLanguage: (lang: string) => void;
  t: (path: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, any>> = {
  ES: {
    common: {
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      create: 'Crear',
      confirm: 'Confirmar',
      close: 'Cerrar',
      search: 'Buscar...',
      loading: 'Cargando...',
      active: 'ACTIVO',
      inactive: 'INACTIVO',
      available: 'DISPONIBLE',
      occupied: 'OCUPADA',
      total: 'Total',
      actions: 'Acciones',
      status: 'Estado',
      print: 'Imprimir',
      notes: 'Observaciones',
      system: 'SISTEMA',
      all: 'Todos',
    },
    nav: {
      yourRestaurant: 'Tu Restaurante',
      management: 'Gestión',
      tables: 'Mesas / Salón',
      menu: 'Productos / Menú',
      kitchen: 'Cocina / KDS',
      settings: 'Configuración',
      reports: 'Reportes y Ventas',
      users: 'Personas / Personal',
      logout: 'Cerrar Sesión',
    },
    tables: {
      title: 'Salón y Mesas',
      subtitle: 'Gestión visual del estado de mesas y toma de comandas.',
      addTable: '+ Agregar Mesa',
      table: 'Mesa',
      capacity: 'Capacidad',
      persons: 'personas',
      viewOrder: 'Ver comanda ➔',
      stagingTitle: '🔥 Nuevos Platos a Enviar',
      stagingEmpty: 'Selecciona platos del menú a la derecha para agregarlos a la comanda.',
      sendToKitchen: 'Enviar a Cocina',
      sending: 'Enviando a Cocina...',
      items: 'ítems',
      confirmedTitle: '📋 Consumo Confirmado en Mesa',
      confirmedEmpty: 'No hay consumos previos registrados en esta mesa.',
      catalogTitle: 'Carta del Restaurante',
      searchPlates: '🔍 Buscar plato o bebida...',
      allCategories: 'Todas',
      totalAccount: 'Total Cuenta:',
      billPreview: 'Sacar Precuenta',
      billTitle: 'PRECUENTA',
      printTicket: '🖨️ Imprimir Ticket',
      checkoutBtn: '💳 Cobrar / Cerrar Mesa',
      closePanel: 'Cerrar Panel',
      checkoutTitle: 'Cobrar y Liberar Mesa',
      totalToPay: 'Total a Cancelar:',
      paymentMethod: 'Método de Pago',
      cash: '💵 Efectivo',
      card: '💳 Tarjeta / POS',
      receivedCash: 'Efectivo Recibido',
      change: 'Vuelto:',
      confirmPayment: '✓ Confirmar Pago',
      newTableTitle: 'Nueva Mesa',
      editTableTitle: 'Editar Mesa',
      tableNumberLabel: 'Número de Mesa',
      tableCapacityLabel: 'Capacidad (Personas)',
      confirmDelete: '¿Eliminar Mesa?',
    },
    categoryModal: {
      createTitle: 'Crear Nueva Categoría',
      editTitle: 'Editar Categoría',
      nameLabel: 'NOMBRE DE LA CATEGORÍA',
      namePlaceholder: 'Ej. Entradas, Bebidas, Postres',
      descLabel: 'DESCRIPCIÓN (OPCIONAL)',
      descPlaceholder: 'Breve descripción del grupo de platos...',
      saveBtn: 'Guardar Categoría',
    },
    productModal: {
      createTitle: 'Crear Nuevo Plato',
      editTitle: 'Editar Plato',
      nameLabel: 'NOMBRE DEL PLATO',
      namePlaceholder: 'Ej. Lomo Saltado',
      categoryLabel: 'CATEGORÍA',
      selectCategory: '-- Seleccionar Categoría --',
      priceLabel: 'PRECIO',
      originalPriceLabel: 'PRECIO ANTERIOR',
      optionalPlaceholder: 'Opcional',
      descLabel: 'DESCRIPCIÓN',
      descPlaceholder: 'Ingredientes o detalles...',
      imageLabel: 'URL IMAGEN (OPCIONAL)',
      discountLabel: 'ETIQUETA DESCUENTO',
      discountPlaceholder: 'Ej. -15%',
      isNew: 'NUEVO',
      isGlutenFree: 'SIN GLUTEN',
      isAvailable: 'Plato disponible para venta',
      saveBtn: 'Guardar Plato',
    },
    menu: {
      title: 'Gestión de Carta y Menú',
      subtitle: 'Administra platos, precios (€) y categorías.',
      newProduct: '+ Nuevo Plato',
      newCategory: '+ Nueva Categoría',
      searchPlaceholder: 'Buscar plato por nombre...',
      allCategory: 'Todos',
      category: 'Categoría',
      price: 'Precio',
      status: 'Estado',
      available: 'DISPONIBLE',
      outOfStock: 'AGOTADO',
      editDish: 'Editar Plato',
      newDish: 'Nuevo Plato',
      dishName: 'Nombre del Plato',
      dishPrice: 'Precio (€)',
      dishCategory: 'Categoría',
      dishDesc: 'Descripción',
      dishImage: 'URL de Imagen',
      saveDish: 'Guardar Plato',
    },
    kitchen: {
      title: 'Monitor de Cocina (KDS)',
      subtitle: 'Comandas en tiempo real para preparación y despacho.',
      allTab: 'Todos',
      pendingTab: 'Pendientes',
      inPrepTab: 'En Marcha',
      allCaughtUp: '¡Cocina al día!',
      noOrders: 'No hay comandas pendientes en este momento. Las nuevas órdenes ingresarán automáticamente.',
      startPrep: 'Comenzar Preparación',
      markReady: '✓ Marcar como Listo',
      markDelivered: '✓ Despachar Comanda',
      order: 'Comanda',
      table: 'Mesa',
      alarmOn: 'Alarma ON',
      alarmOff: 'Alarma OFF',
      hallTime: 'Hora Salón',
    },
    reports: {
      title: 'Panel de Ventas y Caja',
      subtitle: 'Control de facturación en tiempo real, arqueo de caja y emisión de descargos oficiales.',
      refresh: 'Actualizar',
      shiftOpen: '● TURNO ABIERTO',
      registerClosed: '🔒 CAJA CERRADA',
      closeRegister: '🔒 Cerrar Caja del Día',
      startNewDay: '🌅 Empezar Nuevo Día',
      officialReport: '📑 Descargo Oficial Imprimible',
      todaySales: 'VENTAS DE HOY',
      thisWeek: 'ESTA SEMANA',
      thisMonth: 'ESTE MES',
      annualSales: 'VENTA ANUAL',
      paidOrdersCount: 'comandas pagadas',
      totalAccounts: 'COMANDAS TOTALES ATENDIDAS',
      totalAccountsCount: 'cuentas',
      avgTicket: 'TICKET PROMEDIO POR MESA',
      last7Days: 'VENTAS DE LOS ÚLTIMOS 7 DÍAS',
      topRotation: 'TOP 5 PLATOS CON MAYOR ROTACIÓN',
      unitsSold: 'unidades vendidas',
      closeRegisterTitle: 'Cierre de Caja del Día (Cierre Z)',
      closeRegisterSubtitle: 'Conciliación de ingresos y conteo de efectivo físico',
      totalBilledToday: 'Total Ventas Facturadas Hoy:',
      initialCash: 'Fondo Inicial de Caja:',
      theoreticalCash: 'Efectivo Total Teórico Esperado:',
      countedCash: 'Efectivo Físico Real Contado en Gaveta:',
      difference: 'Diferencia (Sobrante/Faltante):',
      notesPlaceholder: 'Ej. Cuadre exacto / Billetes guardados...',
      confirmCloseBtn: '🔒 Confirmar Cierre de Caja',
      daily: '☀️ Diario',
      weekly: '📅 Semanal',
      monthly: '🗓️ Mensual',
      annual: '📈 Anual',
      docOfficial: 'DOCUMENTO OFICIAL DE DESCARGO DE VENTAS',
      issueDate: 'Fecha de Emisión:',
      periodBilled: 'Facturación del Período:',
      issuer: 'Responsable / Emisor:',
      cashierSign: 'Responsable de Caja / POS',
      auditorSign: 'Administración General',
      stamp: 'Firma y Sello',
      printPeriodReport: '🖨️ Imprimir Descargo',
    },
    settings: {
      title: 'Configuración del Restaurante',
      subtitle: 'Personaliza la identidad de tu negocio, logo externo, moneda, precuenta e idioma del sistema.',
      resetValues: 'Restaurar Valores',
      saveChanges: '💾 Guardar Cambios',
      tabIdentity: 'Identidad y Marca',
      tabCurrency: 'Moneda e Impuestos',
      tabTickets: 'Precuenta y Tickets',
      tabSystem: 'Idioma y Sistema',
      sectionBusiness: 'DATOS DE LA EMPRESA Y LOGOTIPO',
      businessName: 'NOMBRE COMERCIAL DEL RESTAURANTE',
      slogan: 'ESLOGAN O SUBTÍTULO',
      logoUrl: 'URL DE IMAGEN EXTERNA (PNG, JPG, SVG)',
      logoFallback: 'INICIAL DE RESPALDO (SI NO HAY IMAGEN O FALLA EL ENLACE)',
      taxId: 'RUC / NIF / CIF (IDENTIFICADOR FISCAL)',
      phone: 'TELÉFONO / WHATSAPP',
      email: 'CORREO ELECTRÓNICO',
      address: 'DIRECCIÓN DEL LOCAL',
      saveConfigBtn: 'GUARDAR CONFIGURACIÓN',
      ticketPreview: 'VISTA PREVIA DEL TICKET',
      currencyConfigured: 'Moneda configurada:',
      noFiscalNotice: 'DOCUMENTO NO VÁLIDO COMO FACTURA FISCAL',
    },
    users: {
      title: 'Gestión de Personas y Roles',
      subtitle: 'Administra usuarios, PIN de acceso y roles con permisos a medida.',
      newRole: '+ Nuevo Rol Personalizado',
      newUser: '+ Nuevo Usuario',
      rolesConfigured: 'ROLES CONFIGURADOS EN EL SISTEMA',
      name: 'NOMBRE',
      email: 'CORREO',
      role: 'ROL / NIVEL',
      pin: 'PIN POS',
      status: 'ESTADO',
      actions: 'ACCIONES',
      activate: 'Activar',
      deactivate: 'Desactivar',
      permissionsCount: 'Permisos:',
      noDesc: 'Sin descripción adicional.',
      systemBadge: 'SISTEMA',
    },
    kiosk: {
      selectMode: '¿Cómo deseas disfrutar tu pedido hoy?',
      takeaway: 'Para Llevar',
      takeawayDesc: 'Pide directamente, paga al instante y recoge sin hacer cola en caja.',
      dineIn: 'Comer en el Salón',
      dineInDesc: 'Elige tu mesa, ordena desde la pantalla y te lo llevamos listo.',
      systemNotice: '⚡ Sistema de Autoservicio Digital • Tu comanda se enviará a cocina tras confirmar el pago.',
      changeMode: '✕ Cambiar Modo',
      selectTable: '🪑 Selecciona tu Mesa en el Salón:',
      chooseTableOption: '-- Elige el número de tu mesa --',
      capacityLabel: 'Capacidad',
      peopleLabel: 'personas',
      searchPlaceholder: '🔍 ¿Qué se te antoja hoy? (Hamburguesas, Bebidas, Postres...)',
      allOptions: 'Todas las Opciones',
      add: '+ Agregar',
      myTray: 'Mi Bandeja',
      emptyTray: 'Aún no has agregado platos a tu bandeja.',
      clear: 'Vaciar',
      unitPrice: 'c/u',
      totalPay: 'Total a Pagar:',
      payAndSend: 'Pagar y Enviar a Cocina',
      selectMesaAlert: '⚠️ Por favor selecciona tu número de mesa arriba para continuar.',
      gatewayBadge: 'Pasarela de Pago Segura',
      gatewayTitle: 'Confirmación de Pago',
      gatewaySubtitle: 'Elige tu medio de pago para procesar la comanda directamente a cocina.',
      amountTotal: 'Monto Total:',
      customerNameLabel: 'Nombre del Cliente (Para llamarte cuando esté listo):',
      customerNamePlaceholder: 'Ej. Juan Pérez',
      paymentMethodLabel: 'Medio de Pago',
      cardPos: 'Tarjeta/POS',
      qrYape: 'QR / Yape',
      cash: 'Efectivo',
      processingPayment: 'Procesando Pago...',
      confirmPaymentBtn: '✓ Confirmar Pago',
      successBadge: '¡Pago Confirmado con Éxito!',
      inKitchen: 'Comanda en Cocina',
      kitchenPrepDesc: 'Nuestro equipo culinario ya está preparando tus platos.',
      pickupNumberLabel: 'Número de Retiro / Mesa',
      takeawayBadge: 'LLEVAR',
      orderAnother: 'Hacer Otro Pedido',
      loading: 'Cargando experiencia de autoservicio...',
    },
  },
  EN: {
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      confirm: 'Confirm',
      close: 'Close',
      search: 'Search...',
      loading: 'Loading...',
      active: 'ACTIVE',
      inactive: 'INACTIVE',
      available: 'AVAILABLE',
      occupied: 'OCCUPIED',
      total: 'Total',
      actions: 'Actions',
      status: 'Status',
      print: 'Print',
      notes: 'Notes',
      system: 'SYSTEM',
      all: 'All',
    },
    nav: {
      yourRestaurant: 'Your Restaurant',
      management: 'Management',
      tables: 'Tables / Dining Room',
      menu: 'Products / Menu',
      kitchen: 'Kitchen / KDS',
      settings: 'Settings',
      reports: 'Sales & Reports',
      users: 'Staff / Users',
      logout: 'Log Out',
    },
    tables: {
      title: 'Dining Room & Tables',
      subtitle: 'Visual management of tables status and order taking.',
      addTable: '+ Add Table',
      table: 'Table',
      capacity: 'Capacity',
      persons: 'people',
      viewOrder: 'View Order ➔',
      stagingTitle: '🔥 New Items to Send',
      stagingEmpty: 'Select menu items on the right to add them to the ticket.',
      sendToKitchen: 'Send to Kitchen',
      sending: 'Sending to Kitchen...',
      items: 'items',
      confirmedTitle: '📋 Confirmed Table Orders',
      confirmedEmpty: 'No previous orders registered for this table.',
      catalogTitle: 'Restaurant Menu',
      searchPlates: '🔍 Search dish or beverage...',
      allCategories: 'All',
      totalAccount: 'Total Bill:',
      billPreview: 'Print Pre-Check',
      billTitle: 'PRE-BILL',
      printTicket: '🖨️ Print Receipt',
      checkoutBtn: '💳 Pay & Close Table',
      closePanel: 'Close Panel',
      checkoutTitle: 'Pay & Release Table',
      totalToPay: 'Total to Pay:',
      paymentMethod: 'Payment Method',
      cash: '💵 Cash',
      card: '💳 Card / POS',
      receivedCash: 'Cash Received',
      change: 'Change:',
      confirmPayment: '✓ Confirm Payment',
      newTableTitle: 'New Table',
      editTableTitle: 'Edit Table',
      tableNumberLabel: 'Table Number',
      tableCapacityLabel: 'Capacity (People)',
      confirmDelete: 'Delete Table?',
    },
    menu: {
      title: 'Menu & Product Management',
      subtitle: 'Manage dishes, prices (€), and categories.',
      newProduct: '+ New Dish',
      newCategory: '+ New Category',
      searchPlaceholder: 'Search dish by name...',
      allCategory: 'All',
      category: 'Category',
      price: 'Price',
      status: 'Status',
      available: 'AVAILABLE',
      outOfStock: 'OUT OF STOCK',
      editDish: 'Edit Dish',
      newDish: 'New Dish',
      dishName: 'Dish Name',
      dishPrice: 'Price (€)',
      dishCategory: 'Category',
      dishDesc: 'Description',
      dishImage: 'Image URL',
      saveDish: 'Save Dish',
    },
    
    kitchen: {
      title: 'Kitchen Display System (KDS)',
      subtitle: 'Real-time tickets for food preparation and dispatch.',
      allTab: 'All',
      pendingTab: 'Pending',
      inPrepTab: 'In Prep',
      allCaughtUp: 'Kitchen all caught up!',
      noOrders: 'No pending orders right now. New orders will appear automatically.',
      startPrep: 'Start Preparation',
      markReady: '✓ Mark as Ready',
      markDelivered: '✓ Dispatch Order',
      order: 'Order',
      table: 'Table',
      alarmOn: 'Alarm ON',
      alarmOff: 'Alarm OFF',
      hallTime: 'Hall Time',
    },
    reports: {
      title: 'Sales & Cash Register Dashboard',
      subtitle: 'Real-time sales control, cash reconciliation, and official printable audits.',
      refresh: 'Refresh',
      shiftOpen: '● SHIFT OPEN',
      registerClosed: '🔒 REGISTER CLOSED',
      closeRegister: '🔒 End of Day (Z-Report)',
      startNewDay: '🌅 Start New Day',
      officialReport: '📑 Official Printable Report',
      todaySales: "TODAY'S SALES",
      thisWeek: 'THIS WEEK',
      thisMonth: 'THIS MONTH',
      annualSales: 'ANNUAL SALES',
      paidOrdersCount: 'paid orders',
      totalAccounts: 'TOTAL COMPLETED ORDERS',
      totalAccountsCount: 'accounts',
      avgTicket: 'AVERAGE TICKET PER TABLE',
      last7Days: 'SALES OF THE LAST 7 DAYS',
      topRotation: 'TOP 5 BEST-SELLING DISHES',
      unitsSold: 'units sold',
      closeRegisterTitle: 'End of Day Cash Closing (Z-Report)',
      closeRegisterSubtitle: 'Revenue reconciliation and physical cash counting',
      totalBilledToday: 'Total Sales Today:',
      initialCash: 'Starting Cash Float:',
      theoreticalCash: 'Expected Cash in Drawer:',
      countedCash: 'Actual Physical Cash Counted:',
      difference: 'Difference (Over/Short):',
      notesPlaceholder: 'E.g., Exact balance / Notes stored...',
      confirmCloseBtn: '🔒 Confirm Cash Closing',
      daily: '☀️ Daily',
      weekly: '📅 Weekly',
      monthly: '🗓️ Monthly',
      annual: '📈 Annual',
      docOfficial: 'OFFICIAL SALES AUDIT REPORT',
      issueDate: 'Issued on:',
      periodBilled: 'Period Revenue:',
      issuer: 'Auditor / Issuer:',
      cashierSign: 'Cashier / POS Officer',
      auditorSign: 'General Management',
      stamp: 'Signature & Stamp',
      printPeriodReport: '🖨️ Print Audit Report',
    },
    settings: {
      title: 'Restaurant Settings',
      subtitle: 'Customize business identity, logo, currency, receipt preview, and system language.',
      resetValues: 'Reset Values',
      saveChanges: '💾 Save Changes',
      tabIdentity: 'Identity & Brand',
      tabCurrency: 'Currency & Taxes',
      tabTickets: 'Pre-check & Receipts',
      tabSystem: 'Language & System',
      sectionBusiness: 'COMPANY DETAILS & LOGO',
      businessName: 'RESTAURANT TRADE NAME',
      slogan: 'SLOGAN OR SUBTITLE',
      logoUrl: 'EXTERNAL IMAGE URL (PNG, JPG, SVG)',
      logoFallback: 'FALLBACK INITIAL (IF IMAGE FAILS)',
      taxId: 'TAX ID / VAT NUMBER',
      phone: 'PHONE / WHATSAPP',
      email: 'EMAIL ADDRESS',
      address: 'PHYSICAL ADDRESS',
      saveConfigBtn: 'SAVE CONFIGURATION',
      ticketPreview: 'RECEIPT PREVIEW',
      currencyConfigured: 'Configured Currency:',
      noFiscalNotice: 'NOT VALID AS A FISCAL INVOICE',
    },
    users: {
      title: 'Staff & Roles Management',
      subtitle: 'Manage users, POS PINs, and customized role permissions.',
      newRole: '+ New Custom Role',
      newUser: '+ New User',
      rolesConfigured: 'SYSTEM CONFIGURED ROLES',
      name: 'NAME',
      email: 'EMAIL',
      role: 'ROLE / LEVEL',
      pin: 'POS PIN',
      status: 'STATUS',
      actions: 'ACTIONS',
      activate: 'Activate',
      deactivate: 'Deactivate',
      permissionsCount: 'Permissions:',
      noDesc: 'No additional description.',
      systemBadge: 'SYSTEM',
    },
    categoryModal: {
      createTitle: 'Create New Category',
      editTitle: 'Edit Category',
      nameLabel: 'CATEGORY NAME',
      namePlaceholder: 'E.g., Starters, Drinks, Desserts',
      descLabel: 'DESCRIPTION (OPTIONAL)',
      descPlaceholder: 'Short description of the dish group...',
      saveBtn: 'Save Category',
    },productModal: {
      createTitle: 'Create New Dish',
      editTitle: 'Edit Dish',
      nameLabel: 'DISH NAME',
      namePlaceholder: 'E.g., Grilled Ribeye',
      categoryLabel: 'CATEGORY',
      selectCategory: '-- Select Category --',
      priceLabel: 'PRICE',
      originalPriceLabel: 'ORIGINAL PRICE',
      optionalPlaceholder: 'Optional',
      descLabel: 'DESCRIPTION',
      descPlaceholder: 'Ingredients or details...',
      imageLabel: 'IMAGE URL (OPTIONAL)',
      discountLabel: 'DISCOUNT BADGE',
      discountPlaceholder: 'E.g., -15%',
      isNew: 'NEW',
      isGlutenFree: 'GLUTEN FREE',
      isAvailable: 'Dish available for sale',
      saveBtn: 'Save Dish',
    },
    kiosk: {
      selectMode: 'How would you like to enjoy your order today?',
      takeaway: 'Takeaway',
      takeawayDesc: 'Order directly, pay instantly, and pick up without queuing.',
      dineIn: 'Dine In',
      dineInDesc: 'Pick your table, order from the screen, and we will bring it over.',
      systemNotice: '⚡ Digital Self-Ordering • Your order will be sent to the kitchen after payment confirmation.',
      changeMode: '✕ Change Mode',
      selectTable: '🪑 Select your Table in the Dining Room:',
      chooseTableOption: '-- Choose your table number --',
      capacityLabel: 'Capacity',
      peopleLabel: 'people',
      searchPlaceholder: '🔍 What are you craving today? (Burgers, Drinks, Desserts...)',
      allOptions: 'All Categories',
      add: '+ Add',
      myTray: 'My Tray',
      emptyTray: 'You have not added any dishes yet.',
      clear: 'Clear',
      unitPrice: 'each',
      totalPay: 'Total to Pay:',
      payAndSend: 'Pay & Send to Kitchen',
      selectMesaAlert: '⚠️ Please select your table number above to continue.',
      gatewayBadge: 'Secure Payment Gateway',
      gatewayTitle: 'Payment Confirmation',
      gatewaySubtitle: 'Select your payment method to dispatch your order straight to the kitchen.',
      amountTotal: 'Total Amount:',
      customerNameLabel: 'Customer Name (To call you when ready):',
      customerNamePlaceholder: 'E.g., John Doe',
      paymentMethodLabel: 'Payment Method',
      cardPos: 'Card / POS',
      qrYape: 'QR / Digital Pay',
      cash: 'Cash',
      processingPayment: 'Processing Payment...',
      confirmPaymentBtn: '✓ Confirm Payment',
      successBadge: 'Payment Confirmed!',
      inKitchen: 'Order in Kitchen',
      kitchenPrepDesc: 'Our culinary team is already preparing your dishes.',
      pickupNumberLabel: 'Pickup / Table Number',
      takeawayBadge: 'TAKEAWAY',
      orderAnother: 'Place Another Order',
      loading: 'Loading self-service experience...',
    },
  },
  IT: {
    common: {
      save: 'Salva',
      cancel: 'Annulla',
      delete: 'Elimina',
      edit: 'Modifica',
      create: 'Crea',
      confirm: 'Conferma',
      close: 'Chiudi',
      search: 'Cerca...',
      loading: 'Caricamento...',
      active: 'ATTIVO',
      inactive: 'INATTIVO',
      available: 'DISPONIBILE',
      occupied: 'OCCUPATO',
      total: 'Totale',
      actions: 'Azioni',
      status: 'Stato',
      print: 'Stampa',
      notes: 'Note',
      system: 'SISTEMA',
      all: 'Tutti',
    },
    nav: {
      yourRestaurant: 'Il Tuo Ristorante',
      management: 'Gestione',
      tables: 'Tavoli / Sala',
      menu: 'Prodotti / Menù',
      kitchen: 'Cucina / KDS',
      settings: 'Impostazioni',
      reports: 'Report & Vendite',
      users: 'Personale / Utenti',
      logout: 'Disconnetti',
    },
    tables: {
      title: 'Sala e Tavoli',
      subtitle: 'Gestione visiva dei tavoli e presa comande.',
      addTable: '+ Aggiungi Tavolo',
      table: 'Tavolo',
      capacity: 'Capienza',
      persons: 'persone',
      viewOrder: 'Vedi comanda ➔',
      stagingTitle: '🔥 Nuovi Piatti da Inviare',
      stagingEmpty: 'Seleziona i piatti dal menù a destra per aggiungerli alla comanda.',
      sendToKitchen: 'Invia in Cucina',
      sending: 'Invio in Cucina...',
      items: 'elementi',
      confirmedTitle: '📋 Comande Confermate al Tavolo',
      confirmedEmpty: 'Nessun consumo precedente registrato per questo tavolo.',
      catalogTitle: 'Menù del Ristorante',
      searchPlates: '🔍 Cerca piatto o bevanda...',
      allCategories: 'Tutte',
      totalAccount: 'Totale Conto:',
      billPreview: 'Preconto',
      billTitle: 'PRECONTO',
      printTicket: '🖨️ Stampa Scontrino',
      checkoutBtn: '💳 Incassa / Libera Tavolo',
      closePanel: 'Chiudi Pannello',
      checkoutTitle: 'Incasso e Chiusura Tavolo',
      totalToPay: 'Totale da Saldare:',
      paymentMethod: 'Metodo di Pagamento',
      cash: '💵 Contanti',
      card: '💳 Carta / POS',
      receivedCash: 'Contanti Ricevuti',
      change: 'Resto:',
      confirmPayment: '✓ Conferma Pagamento',
      newTableTitle: 'Nuovo Tavolo',
      editTableTitle: 'Modifica Tavolo',
      tableNumberLabel: 'Numero Tavolo',
      tableCapacityLabel: 'Capienza (Persone)',
      confirmDelete: 'Eliminare il tavolo?',
    },
    menu: {
      title: 'Gestione Menù e Prodotti',
      subtitle: 'Gestisci piatti, prezzi (€) e categorie.',
      newProduct: '+ Nuovo Piatto',
      newCategory: '+ Nuova Categoria',
      searchPlaceholder: 'Cerca piatto per nome...',
      allCategory: 'Tutti',
      category: 'Categoria',
      price: 'Prezzo',
      status: 'Stato',
      available: 'DISPONIBILE',
      outOfStock: 'ESAURITO',
      editDish: 'Modifica Piatto',
      newDish: 'Nuovo Piatto',
      dishName: 'Nome Piatto',
      dishPrice: 'Prezzo (€)',
      dishCategory: 'Categoria',
      dishDesc: 'Descrizione',
      dishImage: 'URL Immagine',
      saveDish: 'Salva Piatto',
    },
    kitchen: {
      title: 'Schermo Cucina (KDS)',
      subtitle: 'Comande in tempo reale per la preparazione e spedizione.',
      allTab: 'Tutti',
      pendingTab: 'In Attesa',
      inPrepTab: 'In Corso',
      allCaughtUp: 'Cucina in pari!',
      noOrders: 'Nessuna comanda in attesa al momento. I nuovi ordini appariranno automaticamente.',
      startPrep: 'Inizia Preparazione',
      markReady: '✓ Segna come Pronto',
      markDelivered: '✓ Consegna Comanda',
      order: 'Comanda',
      table: 'Tavolo',
      alarmOn: 'Allarme ON',
      alarmOff: 'Allarme OFF',
      hallTime: 'Ora Sala',
    },
    reports: {
      title: 'Pannello Vendite e Cassa',
      subtitle: 'Controllo incassi in tempo reale, chiusura cassa e rendiconti ufficiali.',
      refresh: 'Aggiorna',
      shiftOpen: '● TURNO APERTO',
      registerClosed: '🔒 CASSA CHIUSA',
      closeRegister: '🔒 Chiusura Cassa del Giorno',
      startNewDay: '🌅 Inizia Nuovo Giorno',
      officialReport: '📑 Rendiconto Ufficiale Stampabile',
      todaySales: 'VENDITE DI OGGI',
      thisWeek: 'QUESTA SETTIMANA',
      thisMonth: 'QUESTO MESE',
      annualSales: 'VENDITA ANNUALE',
      paidOrdersCount: 'comande saldate',
      totalAccounts: 'COMANDE TOTALI SERVITE',
      totalAccountsCount: 'conti',
      avgTicket: 'SCONTRINO MEDIO PER TAVOLO',
      last7Days: 'VENDITE DEGLI ULTIMI 7 GIORNI',
      topRotation: 'TOP 5 PIATTI PIÙ VENDUTI',
      unitsSold: 'unità vendute',
      closeRegisterTitle: 'Chiusura di Cassa Giornaliera (Chiusura Z)',
      closeRegisterSubtitle: 'Quadratura incassi e conteggio contanti fisici',
      totalBilledToday: 'Totale Incassato Oggi:',
      initialCash: 'Fondo Cassa Iniziale:',
      theoreticalCash: 'Totale Teorico Atteso in Cassa:',
      countedCash: 'Contanti Fisici Effettivi Contati:',
      difference: 'Differenza (Avanzo/Ammanco):',
      notesPlaceholder: 'Es. Quadratura perfetta / Banconote conservate...',
      confirmCloseBtn: '🔒 Conferma Chiusura Cassa',
      daily: '☀️ Giornaliero',
      weekly: '📅 Settimanale',
      monthly: '🗓️ Mensile',
      annual: '📈 Annuale',
      docOfficial: 'DOCUMENTO UFFICIALE RENDICONTO VENDITE',
      issueDate: 'Data di Emissione:',
      periodBilled: 'Fatturato del Periodo:',
      issuer: 'Responsabile / Emittente:',
      cashierSign: 'Responsabile Cassa / POS',
      auditorSign: 'Direzione Generale',
      stamp: 'Firma e Timbro',
      printPeriodReport: '🖨️ Stampa Rendiconto',
    },
    settings: {
      title: 'Impostazioni Ristorante',
      subtitle: 'Personalizza identità aziendale, logo, valuta, anteprima scontrino e lingua del sistema.',
      resetValues: 'Ripristina Valori',
      saveChanges: '💾 Salva Modifiche',
      tabIdentity: 'Identità e Brand',
      tabCurrency: 'Valuta e Imposte',
      tabTickets: 'Preconto e Scontrini',
      tabSystem: 'Lingua e Sistema',
      sectionBusiness: 'DATI AZIENDALI E LOGO',
      businessName: 'RAGIONE SOCIALE RISTORANTE',
      slogan: 'SLOGAN O SOTTOTITOLO',
      logoUrl: 'URL IMMAGINE ESTERNA (PNG, JPG, SVG)',
      logoFallback: 'INIZIALE DI RISERVA (SE MANCA IMMAGINE)',
      taxId: 'PARTITA IVA / CODICE FISCALE',
      phone: 'TELEFONO / WHATSAPP',
      email: 'INDIRIZZO EMAIL',
      address: 'INDIRIZZO SEDE',
      saveConfigBtn: 'SALVA CONFIGURAZIONE',
      ticketPreview: 'ANTEPRIMA SCONTRINO',
      currencyConfigured: 'Valuta configurata:',
      noFiscalNotice: 'DOCUMENTO NON FISCALE',
    },
    users: {
      title: 'Gestione Personale e Ruoli',
      subtitle: 'Gestisci utenti, PIN di accesso e ruoli con permessi personalizzati.',
      newRole: '+ Nuovo Ruolo Personalizzato',
      newUser: '+ Nuovo Utente',
      rolesConfigured: 'RUOLI CONFIGURATI NEL SISTEMA',
      name: 'NOME',
      email: 'EMAIL',
      role: 'RUOLO / LIVELLO',
      pin: 'PIN POS',
      status: 'STATO',
      actions: 'AZIONI',
      activate: 'Attiva',
      deactivate: 'Disattiva',
      permissionsCount: 'Permessi:',
      noDesc: 'Nessuna descrizione aggiuntiva.',
      systemBadge: 'SISTEMA',
    },
    categoryModal: {
      createTitle: 'Crea Nuova Categoria',
      editTitle: 'Modifica Categoria',
      nameLabel: 'NOME DELLA CATEGORIA',
      namePlaceholder: 'Es. Antipasti, Bevande, Dolci',
      descLabel: 'DESCRIZIONE (OPZIONALE)',
      descPlaceholder: 'Breve descrizione del gruppo di piatti...',
      saveBtn: 'Salva Categoria',
    },
    productModal: {
      createTitle: 'Crea Nuovo Piatto',
      editTitle: 'Modifica Piatto',
      nameLabel: 'NOME DEL PIATTO',
      namePlaceholder: 'Es. Risotto ai Funghi',
      categoryLabel: 'CATEGORIA',
      selectCategory: '-- Seleziona Categoria --',
      priceLabel: 'PREZZO',
      originalPriceLabel: 'PREZZO PRECEDENTE',
      optionalPlaceholder: 'Opzionale',
      descLabel: 'DESCRIZIONE',
      descPlaceholder: 'Ingredienti o dettagli...',
      imageLabel: 'URL IMMAGINE (OPZIONALE)',
      discountLabel: 'ETICHETTA SCONTO',
      discountPlaceholder: 'Es. -15%',
      isNew: 'NUOVO',
      isGlutenFree: 'SENZA GLUTINE',
      isAvailable: 'Piatto disponibile per la vendita',
      saveBtn: 'Salva Piatto',
    },
    kiosk: {
      selectMode: 'Come desideri ordinare oggi?',
      takeaway: 'Da Asporto',
      takeawayDesc: 'Ordina direttamente, paga subito e ritira senza fare la fila.',
      dineIn: 'Al Tavolo in Sala',
      dineInDesc: 'Scegli il tuo tavolo, ordina dallo schermo e ti serviremo noi.',
      systemNotice: '⚡ Sistema Self-Service Digitale • La comanda andrà in cucina dopo la conferma del pagamento.',
      changeMode: '✕ Cambia Modalità',
      selectTable: '🪑 Seleziona il tuo Tavolo in Sala:',
      chooseTableOption: '-- Scegli il numero del tuo tavolo --',
      capacityLabel: 'Capienza',
      peopleLabel: 'persone',
      searchPlaceholder: '🔍 Cosa ti va di gustare oggi? (Burger, Bevande, Dolci...)',
      allOptions: 'Tutte le Opzioni',
      add: '+ Aggiungi',
      myTray: 'Il Mio Vassoio',
      emptyTray: 'Non hai ancora aggiunto piatti al vassoio.',
      clear: 'Svuota',
      unitPrice: 'cad.',
      totalPay: 'Totale da Pagare:',
      payAndSend: 'Paga e Invia in Cucina',
      selectMesaAlert: '⚠️ Seleziona prima il numero del tavolo in alto per continuare.',
      gatewayBadge: 'Gateway di Pagamento Sicuro',
      gatewayTitle: 'Conferma del Pagamento',
      gatewaySubtitle: 'Scegli il metodo di pagamento per inoltrare la comanda direttamente in cucina.',
      amountTotal: 'Importo Totale:',
      customerNameLabel: 'Nome Cliente (Per chiamarti quando è pronto):',
      customerNamePlaceholder: 'Es. Mario Rossi',
      paymentMethodLabel: 'Metodo di Pagamento',
      cardPos: 'Carta / POS',
      qrYape: 'QR / Digitale',
      cash: 'Contanti',
      processingPayment: 'Elaborazione Pagamento...',
      confirmPaymentBtn: '✓ Conferma Pagamento',
      successBadge: 'Pagamento Confermato con Successo!',
      inKitchen: 'Comanda in Cucina',
      kitchenPrepDesc: 'La nostra brigata di cucina sta già preparando i tuoi piatti.',
      pickupNumberLabel: 'Numero Ritiro / Tavolo',
      takeawayBadge: 'ASPORTO',
      orderAnother: 'Fai un Altro Ordine',
      loading: 'Caricamento esperienza self-service...',
    },
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    const upper = String(saved || 'ES').toUpperCase();
    if (upper === 'ES' || upper === 'EN' || upper === 'IT') return upper as Language;
    return 'ES';
  });

  const setLanguage = (lang: string) => {
    const upper = String(lang || 'ES').toUpperCase() as Language;
    const finalLang = upper === 'ES' || upper === 'EN' || upper === 'IT' ? upper : 'ES';
    setLanguageState(finalLang);
    localStorage.setItem('app_language', finalLang);
  };

  const t = (path: string, fallback?: string): string => {
    const currentLang = language || 'ES';
    const keys = path.split('.');
    let current: any = translations[currentLang];

    for (const key of keys) {
      if (current && typeof current === 'object' && key in current) {
        current = current[key];
      } else {
        return fallback || path;
      }
    }

    return typeof current === 'string' ? current : fallback || path;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, changeLanguage: setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage debe ser usado dentro de un LanguageProvider');
  }
  return context;
};